{
 "title": "Metric demo",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU A",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad{job=\"sample-rest-service-a\"}"
    }
   ]
  },
  {
   "title": "Thread A",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{job=\"sample-rest-service-a\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "base_thread_max_count{job=\"sample-rest-service-a\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Memory A",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{job=\"sample-rest-service-a\"}"
    }
   ]
  },
  {
   "title": "Datasource A",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wildfly_datasources_pool_active_count{job=\"sample-rest-service-a\"}",
     "legendFormat": "Active pool"
    },
    {
     "expr": "wildfly_datasources_pool_in_use_count{job=\"sample-rest-service-a\"}",
     "legendFormat": "Pool in use"
    }
   ]
  },
  {
   "title": "GC A",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(base_gc_time_total_seconds{job=\"sample-rest-service-a\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "demo entity count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "application_DEMO_total" }
   ]
  },
  {
   "title": "demo rest response time per sec",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_sample_http_response_time_fifteen_min_rate_per_second"
    }
   ]
  },
  {
   "title": "demo rest response time sum",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_sample_http_response_time_seconds_sum"
    }
   ]
  }
 ]
}