{
 "title": "Trace dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU A and B",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad{job=\"sample-rest-service-a\"}"
    },
    {
     "expr": "base_cpu_processCpuLoad{job=\"sample-rest-service-b\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Datasource A",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wildfly_datasources_pool_active_count{job=\"sample-rest-service-a\"}",
     "legendFormat": "Active pool"
    },
    {
     "expr": "wildfly_datasources_pool_in_use_count{job=\"sample-rest-service-a\"}",
     "legendFormat": "Pool in use"
    }
   ]
  },
  {
   "title": "B service trace",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "limit": 100, "service": "demoB" }
   ]
  },
  {
   "title": "Datasource B",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wildfly_datasources_pool_active_count{job=\"sample-rest-service-b\"}",
     "legendFormat": "Active pool"
    },
    {
     "expr": "wildfly_datasources_pool_in_use_count{job=\"sample-rest-service-b\"}",
     "legendFormat": "Pool in use"
    }
   ]
  }
 ]
}