version: "3.8"

# execution
# docker-compose -f <PROJECT_PATH>/backend-sampler/etc/docker-compose/docker-compose.local.demoB.yml up --build --force-recreate
services:
  sample-service-b:
    container_name: sample-rest-service-local-b
    build:
      context: .
      dockerfile: develop.dockerfile
      args:
        WILDFLY_BASE_IMAGE: 'dockerhub.icellmobilsoft.hu/wildfly-full/postgresql-jdbc:0.6.0'
        WILDFLY_CLI_PATH: wildfly/*.*
    volumes:
      - './wildfly/wf.properties:/appconfig/app.properties'
    ports:
      - '8082:8080'
      - '9992:9990'
      - '8789:8787'
    environment:
      OPENTRACING_JAEGER_AGENT_HOST: jaeger
      JAEGER_SERVICE_NAME: demoB
      POSTGRESQL_DS_MAX_POOL_SIZE: 50
      OPENTRACING_JAEGER_PROPAGATION: JAEGER
#      MP_CONFIG_PROFILE: local
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
networks: 
  default: 
    external: 
      name: bs-local-network
